### ISSUE TITLE
求教音视频同步播放问题

### ISSUE THREAD

**Issue by MingoJiang** [kinpol/singleWfsjs#2]
你好， 怎么解决音视频同步播放问题？
websocket推流过来的不仅仅是h264，还有G711A音频流，应该怎么与视频同步播放，麻烦指点一下，谢谢。

**Comment by kinpol** [comment]
我们音频暂时没有处理，但是根据你的问题，我们这里在做视频结构化的时候，也存在这个问题。在websocket传输视频帧的同时，推送结构化信息，也就是一帧视频数据，一帧结构化信息。这样解决视频和信息的同步。最简单的方式，就是一帧视频数据，一帧音频数据。前端收到之后，送各自解码器。
