### ISSUE TITLE
关于播放13个小时15分钟21秒，出现视频卡顿的问题

### ISSUE THREAD

**Issue by zhang22113** [kinpol/singleWfsjs#4]
每当我的视频播放到13个小时15分钟21秒时，视频就会卡住，不是因为内存溢出。但是具体原因也不是很清楚

**Comment by kinpol** [comment]
1. vlc查看那个时刻的视频，是不是也这样。
2. 看一下buffered.end(0)和played.end(0)是不是一致。
https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLMediaElement/buffered
4. 如果一致，那就是断流了，视频卡住。否则，是内存堆积。堆积的话，及时清理缓存。详细的代码里面有

**Comment by zhang22113** [comment]
> 1. vlc查看那个时刻的视频，是不是也这样。
> 2. 看一下buffered.end(0)和played.end(0)是不是一致。
>    https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLMediaElement/buffered
> 3. 如果一致，那就是断流了，视频卡住。否则，是内存堆积。堆积的话，及时清理缓存。详细的代码里面有

您好，首先sourceBuffer.buffered.end(0)和media.played.end(0),media.played.end(0)一直没有什么变化。再者，内存堆积的代码，我没找到，不知道具体是哪一段呢？

**Comment by zhang22113** [comment]
> > 1. vlc查看那个时刻的视频，是不是也这样。
> > 2. 看一下buffered.end(0)和played.end(0)是不是一致。
> >    https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLMediaElement/buffered
> > 3. 如果一致，那就是断流了，视频卡住。否则，是内存堆积。堆积的话，及时清理缓存。详细的代码里面有
> 
> 您好，首先sourceBuffer.buffered.end(0)和media.played.end(0),media.played.end(0)一直没有什么变化。再者，内存堆积的代码，我没找到，不知道具体是哪一段呢？

**Comment by kinpol** [comment]
好吧，简单点儿在时间是47721的时候，reload。可能是溢出的问题，但是不是内存溢出(或者google的策略？)可以在firefox中，对比测试。

**Comment by zhang22113** [comment]
> 好吧，简单点儿在时间是47721的时候，reload。可能是溢出的问题，但是不是内存溢出(或者google的策略？)可以在firefox中，对比测试。

应该不是内存溢出吧，因为我有对sourceBuffer做处理，在任务管理器上面并没有看到问题。毕竟浏览器并没有崩溃
